In [1]:
import numpy as np

In [9]:
m = np.zeros((10, 10 + 1))

In [241]:
def greedy_naive_solution(n, weights):
    cliques = []
    edges = [(i, j, weights[i][j]) for i in range(n) for j in range(i + 1, n)]
    edges.sort(key=lambda x: x[-1], reverse=True)
    used_edges = []
    while edges:
        new_clique = []
        edge = edges.pop(0)
        new_clique.append(edge)
        for e in edges[:]:
            if not any((e[0] in pair or e[1] in pair) for pair in used_edges):
                new_clique.append(e)
                used_edges.append(e)
                break
            edges.remove(e)
        cliques.append(new_clique)
    naive_sol = {}
    for clique in cliques:
        for i, j, w in clique:
            naive_sol[(i, j)] = 1
    return naive_sol

In [243]:
test_n = 6
test_w = [[-10, -3, -10, 4, -6, -1], 
          [10, -9, -10, 3, -4, 4], 
          [8, 0, -3, -2, -2, 4], 
          [0, -9, 9, 7, -5, -4], 
          [-5, 4, -5, 2, 8, 1], 
          [6, -1, 10, 10, 3, -3]]

init_solution = greedy_naive_solution(test_n, test_w)

In [245]:
init_solution

{(0, 3): 1, (1, 5): 1, (2, 3): 1}

In [247]:
# cliques = {}
for cliq_idx in init_solution.keys():
    print(cliq_idx)

(0, 3)
(1, 5)
(2, 3)


In [ ]:
class MatrixCPP(cliques, w, n):
    # self.matrix
    def __init__(cliques, w, n):
        self.matrix = initialize_matrix(cliques, w, n)
        return
        
    def initialize_matrix(cliques, w, n):
        m = np.zeros((n, n + 1))
    
        for cliq_idx in cliques.keys():
            # для вершин не входящих в эту клику заполнить потенциальность включения
            # для вершин из клики - ?
    
        return m
        
    def modify_matrix(cliques, w, n):
    
        for cliq_idx in cliques.keys():
            # для вершин не входящих в эту клику заполнить потенциальность включения
            # для вершин из клики - ?
            
        return

(0, 3)
(1, 5)
(2, 3)


In [185]:
def modify_matrix(m, w, cliques, n, num_cliques, i, j, k):
    # i - индекс строки перемещаемой вершины
    # k - индекс клики куда, j - индекс клики откуда
    
    # изменение двух эл-тов строки перемещаемой вершины
    m[i, j], m[i, k] = m[i, j] + m[i, k], m[i, k] - m[i, k]

    # изменение клик "откуда" и "куда"
    for idx in range(n):
        if idx != i:
            edge = [i, idx] if i < idx else [idx, i]
            m[idx, j] += w[* edge]
            m[idx, k] -= w[* edge]

    # изменение строк соседей по клике "откуда"
    for cliq_idx in cliques.keys():
        # для вершин входящих в эту клику изменить потенциальность включения в др. клики
        continue

    # изменение соседей по клике "куда" (?)
        
    return m

In [233]:
# [x - test_w[0][3] for x in test_w[0]]
a, b = 1, 2
print(f'a = {a} \t b = {b}')
print([a, b] if a < b else [b, a])

a, b = b, a
print(f'a = {a} \t b = {b}')
print([a, b] if a < b else [b, a])

a = 1 	 b = 2
[1, 2]
a = 2 	 b = 1
[1, 2]


In [107]:
e = [a, b]
w[* e]

3

In [217]:
# пока оч. произвольное
def initial_partition(w):
    cliques = {0: [0, 1], 1: [2, 3], 2: [4]} 
    return cliques

def find_clique(cliques, i):
    for idx, clique in cliques.items():
        if i in clique:
            return idx

def get_delta(w, cliques, cur_clique, new_clique, i):
    delta = 0
    
    for v in cliques[new_clique]:
        delta += w[i][v]
    
    for v in cliques[cur_clique]:
        if v != i: # в целом, эту проверку можно не делать, в эл-те w[i][i] точно ноль, 
            # но кажется что на больших графах без такой проверки будем много лишних операций вычитания делать
            delta -= w[i][v]
            
    return delta


def get_delta_dummy_clique(w, cliques, cur_clique, i):
    gain = 0
    for v in cliques[cur_clique]:
        if v != i: 
            gain -= graph[i][v]
    return gain


def initialize_matrix(w, cliques):
    n = len(w)
    m = len(cliques)
    
    M = np.zeros((n, m + 1))
    
    for i in range(n):
        my_clique = find_clique(cliques, i)
        
        for j in range(m):
            if my_clique != j:
                M[i, j] = get_delta(w, cliques, my_clique, j, i)
        
        # отдельно, т.к. фиктивных клик нет в словаре cliques
        M[i, m] = get_delta_dummy_clique(w, cliques, my_clique, i)
    
    return M


def obj_function(w, cliques):
    total_weight = 0
    
    for clique in cliques.values():
        for i in clique:
            for j in clique:
                if i != j and i < j:
                    total_weight += w[i][j]
                    
    return total_weight

In [181]:
# def modify_matrix(M, w, cliques, n, num_cliques, i, j, k):
#     if k != num_cliques:
        
#     return M

def local_search(w):
    cur_solution = initial_partition(w)
    cur_objective = obj_function(w, cur_solution)
    
    n, num_cliques = len(w), len(cur_solution)
    m = initialize_matrix(w, cur_solution)
    
    while True:
        i, j = np.unravel_index(np.argmax(M), M.shape)
        max_delta = m[i, j]
        
        if max_delta <= 0: # поменять на == 0 (?) тут мб и не надо, а в табу-серч кажется стоит
            break
            
        cur_clique = find_clique(cur_solution, i)
        
        # пересчет матрицы приращений
        m = modify_matrix(m, w, cur_solution, n, num_cliques, i, cur_clique, j)
        
        # обновление словаря клик
        #            вынести в отдельную функцию? или не стоит? что там с памятью...
        if j == m.shape[1] - 1: # создаем новую клику
            new_idx = len(cur_solution)
            cur_solution[new_idx] = [i]
        else:
            cur_solution[cur_clique].remove(i)
            cur_solution[j].append(i)
        
        cur_objective += max_delta # в целом, можно это пересчитать по готовому решению, 
        # мы же не сравниваем по значению целевой функции, но пусть пока будет не нужно будет обходить всю матрицу во второй раз
    
    return cur_solution, cur_objective

In [209]:
graph = np.array([
    [0, 1, 2, 0, 0, 0],
    [1, 0, 3, 1, 1, 0],
    [2, 3, 0, 4, 2, 0],
    [0, 1, 4, 0, 0, 0],
    [0, 1, 2, 0, 0, 15],
])

graph.shape[1]
i, j = np.unravel_index(np.argmax(graph), graph.shape)

if j == graph.shape[1] - 1:
    print(True)

# best_solution = local_search(graph)
# print("лучшее разбиение на клики:", best_solution)

True


In [ ]:
def tabu_search(w, max_k, len_tl):
    cur_solution = initial_partition(w)
    cur_objective = obj_function(w, cur_solution)
    
    tabu_lst, k = set(), 0
    best_solution, best_objective = cur_solution, cur_objective
    
    m = initialize_matrix(w, cur_solution)
    n, num_cliques = len(w), len(cur_solution)

    while k < max_k:
        i, j = np.unravel_index(np.argmax(M), M.shape)
        max_delta = m[i, j]
        
        if max_delta == 0: # не менять на <= 0 (?)
            break
        

    
    return best_solution, best_objective

In [213]:
cliques = {0: [0, 1], 1: [2, 3], 2: [4]}

for k, clique in cliques.items():
    print(f'k {k} \t clique {clique}')

print(f"\nlen(cliques) {len(cliques)}")

k 0 	 clique [0, 1]
k 1 	 clique [2, 3]
k 2 	 clique [4]

len(cliques) 3


In [221]:
w = np.array([
    [0, 1, 2, 0, 3],
    [1, 0, 3, 1, 2],
    [2, 3, 0, 4, 1],
    [0, 1, 4, 0, 5],
    [3, 2, 1, 5, 0]
])
print("\nвеса графа (матрица w):\n", w)

cliques = initial_partition(w)
print("\nпроизвольное начальное разбиение:", cliques)

M = initialize_matrix(w, cliques)
print("\nматрица приращений M:\n", M)

initial_objective = obj_function(w, cliques)
print("\nначальное значение целевой функции:", initial_objective)


веса графа (матрица w):
 [[0 1 2 0 3]
 [1 0 3 1 2]
 [2 3 0 4 1]
 [0 1 4 0 5]
 [3 2 1 5 0]]

произвольное начальное разбиение: {0: [0, 1], 1: [2, 3], 2: [4]}

матрица приращений M:
 [[ 0.  1.  2. -1.]
 [ 0.  3.  1. -1.]
 [ 1.  0. -3. -4.]
 [-3.  0.  1. -4.]
 [ 5.  6.  0.  0.]]

начальное значение целевой функции: 5


In [231]:
w

array([[0, 1, 2, 0, 3],
       [1, 0, 3, 1, 2],
       [2, 3, 0, 4, 1],
       [0, 1, 4, 0, 5],
       [3, 2, 1, 5, 0]])

In [229]:
print(np.argmax(M))

17


In [227]:
print(M)
print(np.argmax(M))
np.unravel_index(np.argmax(M), M.shape)

[[ 0.  1.  2. -1.]
 [ 0.  3.  1. -1.]
 [ 1.  0. -3. -4.]
 [-3.  0.  1. -4.]
 [ 5.  6.  0.  0.]]
17


(4, 1)

In [29]:
list1 = [1, 2, 3, 4]
list2 = [3, 4, 5, 6]

[item for item in list2 if item not in list1]

[5, 6]

In [201]:
get_delta(graph, {0: [0, 1], 1: [2, 3], 2: [4]}, 0, 1, 0)

1