In [5]:
import numpy as np

In [31]:
def greedy_naive_solution(weights, n):
    cliques = []
    edges = [(i, j, weights[i][j]) for i in range(n) for j in range(i + 1, n)]
    edges.sort(key=lambda x: x[-1], reverse=True)
    while edges:
        new_clique = []
        edge = edges.pop(0)
        if edge[2] < 0:
            break
        new_clique.append(edge)
        new_edges = list(filter(lambda e: not (e[0] in edge or e[1] in edge),edges))
        cliques.append(new_clique)
        edges = new_edges
    sol = {}
    for k, clique in enumerate(cliques):
        sol[k] = set()
        for i, j, w in clique:
            sol[k].add(i)
            sol[k].add(j)
    for i, v in enumerate(set(i for i in range(n)) - set().union(*sol.values())):
        sol[i + len(cliques)] = [v]
    for k, clique in enumerate(cliques):
        sol[k] = list(sol[k])
    return sol

In [233]:
from setuptools.config.pyprojecttoml import load_file


def remove_negative_vertices(weights):
    n = len(weights)
    vertex_sums = []
    for i in range(n):
        total = sum(weights[i][j] for j in range(n) if i != j)
        vertex_sums.append(total)

    if vertex_sums and max(vertex_sums) <=0:
        return [min(*[enumerate(vertex_sums)],key=lambda x: x[1])[0]]
    else:
        return [i for i, s in  enumerate(vertex_sums) if s > 0]


def vertex_deleter(weights, n):
    vertexes = set(i for i in range(n))
    cl = []
    remaining_vertices = [1]
    vert_name_map =  dict(zip(range(len(vertexes)), list(vertexes)))
    while len(remaining_vertices) != 0:
        remaining_vertices = remove_negative_vertices(weights)
        if remaining_vertices:
            cl.append(list(map(lambda x: vert_name_map[x], remaining_vertices)))
        weights = [[weights[i][j] for j in range(len(weights)) if j not in remaining_vertices] for i in range(len(weights))
                   if i not in remaining_vertices]
        vertexes -= set(list(map(lambda x: vert_name_map[x], remaining_vertices)))
        vert_name_map = dict(zip(range(len(weights)), vertexes))
    return dict(zip(range(len(cl)), cl))

weights_sasha = np.array(
    [[3.0, 7.0, 8.0, 2.0, 1.0, 8.0, 10.0, -1e+20, 4.0, 5.0], 
     [7.0, 7.0, 10.0, 5.0, 7.0, 7.0, 3.0, 10.0, 6.0, 2.0], 
     [8.0, 10.0, -1e+20, -1e+20, -1e+20, 6.0, 3.0, 6.0, 1.0, 6.0], 
     [2.0, 5.0, -1e+20, 3.0, 3.0, -1e+20, 9.0, 5.0, -1e+20, 8.0], 
     [1.0, 7.0, -1e+20, 3.0, 8.0, -1e+20, -1e+20, 4.0, 5.0, 4.0], 
     [8.0, 7.0, 6.0, -1e+20, -1e+20, 7.0, 3.0, 2.0, 4.0, 9.0], 
     [10.0, 3.0, 3.0, 9.0, -1e+20, 3.0, -1e+20, 4.0, 8.0, 5.0], 
     [-1e+20, 10.0, 6.0, 5.0, 4.0, 2.0, 4.0, 10.0, -1e+20, -1e+20], 
     [4.0, 6.0, 1.0, -1e+20, 5.0, 4.0, 8.0, -1e+20, -1e+20, 8.0], 
     [5.0, 2.0, 6.0, 8.0, 4.0, 9.0, 5.0, -1e+20, 8.0, 8.0]])

vertex_deleter(weights_sasha, 10)


{0: [1], 1: [3], 2: [4], 3: [2, 5, 6], 4: [7], 5: [0, 8, 9]}

In [11]:
test_n = 6
test_w = [[-10, -3, -10, 4, -6, -1], 
          [10, -9, -10, 3, -4, 4], 
          [8, 0, -3, -2, -2, 4], 
          [0, -9, 9, 7, -5, -4], 
          [-5, 4, -5, 2, 8, 1], 
          [6, -1, 10, 10, 3, -3]]

init_solution = greedy_naive_solution(test_w, test_n)

In [13]:
init_solution

{0: [0, 3], 1: [1, 5]}

In [ ]:
class MatrixCPP(cliques, w, n):
    # self.matrix
    
    def __init__(cliques, w, n):
        self.matrix = initialize_matrix(cliques, w, n)
        return
        
    def initialize_matrix(cliques, w, n):
        pass
        
    def modify_matrix(cliques, w, n):
        pass

In [373]:
best_solution = local_search(graph)
print("лучшее разбиение на клики:", best_solution)

[[ 0.  1. -1. -1.]
 [ 0.  4. -1. -1.]
 [-1. -2. -4. -6.]
 [-3.  0. -4. -4.]
 [-1.  0. -2. -2.]]
лучшее разбиение на клики: ({0: [0, 1], 1: [2, 3, 4], 2: []}, 7.0)


In [137]:
lst = [2, 3, 4]
lst.remove(2)
lst

[3, 4]

In [335]:
def get_weights(w, n, v):
    if v == 0:
        return np.concatenate(([0], w[v, 1:]))
    left = w[:v, v]
    right = w[v, v+ 1:] if v < n - 1 else []
    return np.concatenate((left, [0], right)) 

print(sasha_w1[:5, :5], "\n")
for v in range(5):
    print(f"vertex {v}\n weights {get_weights(sasha_w1[:5, :5], 5, v)}\n\n")

[[ 2.e+00  6.e+00  7.e+00 -1.e+20 -1.e+20]
 [ 6.e+00  1.e+01 -1.e+20 -1.e+20 -1.e+20]
 [ 7.e+00 -1.e+20 -1.e+20 -1.e+20  6.e+00]
 [-1.e+20 -1.e+20 -1.e+20  6.e+00  3.e+00]
 [-1.e+20 -1.e+20  6.e+00  3.e+00 -1.e+20]] 

vertex 0
 weights [ 0.e+00  6.e+00  7.e+00 -1.e+20 -1.e+20]


vertex 1
 weights [ 6.e+00  0.e+00 -1.e+20 -1.e+20 -1.e+20]


vertex 2
 weights [ 7.e+00 -1.e+20  0.e+00 -1.e+20  6.e+00]


vertex 3
 weights [-1.e+20 -1.e+20 -1.e+20  0.e+00  3.e+00]


vertex 4
 weights [-1.e+20 -1.e+20  6.e+00  3.e+00  0.e+00]




In [420]:
def get_edge(i, j):
    return [i, j] if i < j else [j, i]

def get_weights(w, n, v):
    if v == 0:
        return np.concatenate(([0], w[v, 1:]))
        
    left = w[:v, v]
    right = w[v, v+ 1:] if v < n - 1 else []
    
    return np.concatenate((left, [0], right))
    
def modify_matrix(m, w, cliques, n, num_cliques, i, j, k):
    # i - индекс вершины, j - индекс клики "откуда", k - индекс клики "куда"
    cur_clique, new_clique = cliques[j], cliques[k]

    m[i] = [x - m[i, k] for x in m[i]]

    # изменение приращений клик "откуда" и "куда" (без учета соседей, им заменим строки целиком)
    for v in range(n):
        # if v not in (cur_clique + new_clique):
        if v != i:
            edge = get_edge(i, v)
            m[v, j] -= w[* edge]

            if k != num_cliques:
                m[v, k] += w[* edge]

    # подшивание столбца
    if k == num_cliques:
        new_column = get_weights(w, n, i)
        for v in range(n):
            if v != i:
                v_weights = get_weights(w, n, v)
                v_weights[i] = 0
                new_column[v] -= sum(v_weights)
        np.insert(m, num_cliques, new_column, axis=1)

    # print(m)
    # убирание столбца
    if len(cur_clique) == 1:
        m = np.delete(m, j, axis=1)
        # print("after removal")
        # print(m)
    
    # пересчет строк соседей
    # print("old_clique \t", cur_clique)
    for v in cur_clique:
        if v != i:
            edge = get_edge(i, v)
            # print("i v ", i, v)
            # print("w[* edge] \t ", w[* edge])
            # print(f"vertex {v} new vals")
            # print([x + w[* edge] for x in m[v]])
            m[v] = [x + w[* edge] for x in m[v]]

    # print("new_clique neighbours \t", new_clique)
    for v in new_clique:
        edge = get_edge(i, v)
        # print("i v ", i, v)
        # print("w[* edge] \t ", w[* edge])
        # print(f"vertex {v} new vals")
        # print([x + w[* edge] for x in m[v]])
        m[v] = [x - w[* edge] for x in m[v]]
    
    return m

In [171]:
list1 = [1, 2, 3]
list2 = [4, 5, 6]

if 9 not in (list1 + list2):
    print(True)
np.zeros(7)

True


array([0., 0., 0., 0., 0., 0., 0.])

In [291]:
matrix = np.array([[1, 2], [3, 4], [5, 6]])
new_column = np.array([7, 8, 9])
# np.column_stack((matrix, new_column))
print(matrix.shape)
np.insert(matrix, matrix.shape[1] - 1, new_column, axis=1)

(3, 2)


array([[1, 7, 2],
       [3, 8, 4],
       [5, 9, 6]])

In [233]:
# [x - test_w[0][3] for x in test_w[0]]
a, b = 1, 2
print(f'a = {a} \t b = {b}')
print([a, b] if a < b else [b, a])

a, b = b, a
print(f'a = {a} \t b = {b}')
print([a, b] if a < b else [b, a])

a = 1 	 b = 2
[1, 2]
a = 2 	 b = 1
[1, 2]


In [275]:
# cliques = {0: [0, 1], 1: [2, 3], 2: [4]}
# print(cliques.keys())

In [107]:
e = [a, b]
w[* e]

3

In [205]:
def find_clique(cliques, i):
    for idx, clique in cliques.items():
        if i in clique:
            return idx

def get_delta(w, cliques, cur_clique, new_clique, i):
    delta = 0
    
    for v in cliques[new_clique]:
        edge = get_edge(i, v)
        delta += w[* edge]
    
    for v in cliques[cur_clique]:
        if v != i: # в целом, эту проверку можно не делать, в эл-те w[i][i] точно ноль, 
            # но кажется что на больших графах без такой проверки будем много лишних операций вычитания делать
            edge = get_edge(i, v)
            delta -= w[* edge]
            
    return delta

# def get_edge(i, j):
#     return [i, j] if i < j else [j, i]

def get_delta_dummy_clique(w, cliques, cur_clique, i):
    delta = 0
    for v in cliques[cur_clique]:
        if v != i: 
            edge = get_edge(i, v)
            delta -= w[* edge]
    return delta


def initialize_matrix(w, cliques):
    n = len(w)
    num_cliques = len(cliques)
    
    m = np.zeros((n, num_cliques + 1))
    
    for i in range(n):
        my_clique = find_clique(cliques, i)
        
        for j in range(num_cliques):
            if my_clique != j:
                m[i, j] = get_delta(w, cliques, my_clique, j, i)
        
        # отдельно, т.к. фиктивных клик нет в словаре cliques
        m[i, num_cliques] = get_delta_dummy_clique(w, cliques, my_clique, i)
    
    return m


def obj_function(w, cliques):
    total_weight = 0
    
    for clique in cliques.values():
        for i in clique:
            for j in clique:
                if i != j and i < j:
                    total_weight += w[i][j]
                    
    return total_weight

In [492]:
def local_search(w, n, constructive_func, save_iters=False):
    cur_solution = constructive_func(w, n)
    
    cur_objective = obj_function(w, cur_solution)
    # print(f'initial cliques : \n{cur_solution}\n')
    
    n, num_cliques = len(w), len(cur_solution)
    m = initialize_matrix(w, cur_solution)
    # print(f'initial m : \n{m}\n')

    if save_iters:
        iter = 0
        deltas = [cur_objective]
        
    while True:
        i, j = np.unravel_index(np.argmax(m), m.shape)
        max_delta = m[i, j]
        # print(f'максимальное приращение на итерации {iter}: {max_delta}')
        # print(f'предыдущее значение ц.ф.: {cur_objective}')
        # print(f'v {i} \t old_clique {find_clique(cur_solution, i)} \t new_clique {j}\n')
        # print(f'cur obj val {cur_objective}, \ncur cliques {cur_solution}')
        # print(f'iter-{iter} m : \n{m}\n')
        
        if max_delta == 0: # поменять на <= 0 (?)
            break
        # if iter >= 20:
        #     break
            
        cur_clique = find_clique(cur_solution, i)
        
        # пересчет матрицы приращений
        m = modify_matrix(m, w, cur_solution, n, num_cliques, i, cur_clique, j)
        
        # обновление словаря клик
        #            вынести в отдельную функцию? или не стоит? что там с памятью...
        # print(f"cur_solution {cur_solution}")
        # print(f"i = {i} \t cur_solution[cur_clique] {cur_solution[cur_clique]}")
        cur_solution[cur_clique].remove(i)

        needs_reindex = False
        if not cur_solution[cur_clique]:
            del cur_solution[cur_clique]
            needs_reindex = True
        if j == m.shape[1]: # создаем новую клику
            print(f"j={j} \t m.shape[1]={m.shape[1]}")
            new_idx = len(cur_solution)
            cur_solution[new_idx] = [i]
        else:
            cur_solution[j].append(i)
        
        if needs_reindex:
            # переиндексация ключей после удаления пустой клики
            old_keys = list(cur_solution.keys())
            for new_idx, old_key in enumerate(old_keys):
                cur_solution[new_idx] = cur_solution.pop(old_key)
                
        # print(f"cur_solution {cur_solution}")

        # print(f'iter-{iter} end-m : \n{m}\n\n')
        cur_objective += max_delta # в целом, можно это пересчитать по готовому решению, 
        # мы же не сравниваем по значению целевой функции, но пусть пока будет не нужно будет обходить всю матрицу во второй раз
        
        if save_iters:
            deltas.append(max_delta)
            iter += 1
            
    return (cur_solution, cur_objective) if not save_iters else (cur_solution, cur_objective, deltas)



In [500]:
test_w_1

array([[ 0, -4, 18, -1, 12],
       [ 0,  0, -5,  6, -2],
       [ 0,  0,  0,  2, 17],
       [ 0,  0,  0,  0, 15],
       [ 0,  0,  0,  0,  0]])

In [502]:
test_n_1

5

In [494]:
# best_solution = local_search(symmetric_test_w_1, test_n_1, greedy_naive_solution)
best_solution = local_search(test_w_1, test_n_1, greedy_naive_solution, save_iters=True)
# best_solution = local_search(w2)
print("лучшее разбиение на клики:", best_solution)

лучшее разбиение на клики: ({0: [0, 2, 4, 3], 1: [1]}, 63.0, [33, 14.0, 16.0])


In [498]:
from itertools import accumulate

print(sum([33, 14.0, 16.0]))
list(accumulate([33, 14.0, 16.0]))

63.0


[33, 47.0, 63.0]

In [468]:
sasha_n1 = 10
sasha_w1 = np.array([[2.0, 6.0, 7.0, -1e+20, -1e+20, -1e+20, -1e+20, 6.0, 3.0, -1e+20], 
             [6.0, 10.0, -1e+20, -1e+20, -1e+20, 3.0, -1e+20, -1e+20, 3.0, -1e+20], 
             [7.0, -1e+20, -1e+20, -1e+20, 6.0, 7.0, -1e+20, -1e+20, -1e+20, -1e+20], 
             [-1e+20, -1e+20, -1e+20, 6.0, 3.0, -1e+20, -1e+20, 4.0, -1e+20, -1e+20], 
             [-1e+20, -1e+20, 6.0, 3.0, -1e+20, 9.0, -1e+20, -1e+20, -1e+20, -1e+20], 
             [-1e+20, 3.0, 7.0, -1e+20, 9.0, -1e+20, 10.0, 5.0, 4.0, 6.0],
             [-1e+20, -1e+20, -1e+20, -1e+20, -1e+20, 10.0, -1e+20, -1e+20, 10.0, 10.0], 
             [6.0, -1e+20, -1e+20, 4.0, -1e+20, 5.0, -1e+20, 6.0, 10.0, 1.0], 
             [3.0, 3.0, -1e+20, -1e+20, -1e+20, 4.0, 10.0, 10.0, -1e+20, -1e+20], 
             [-1e+20, -1e+20, -1e+20, -1e+20, -1e+20, 6.0, 10.0, 1.0, -1e+20, 3.0]])

# sasha_best_solution_1 = local_search(sasha_w1, sasha_n1, greedy_naive_solution)
sasha_best_solution_1 = local_search(sasha_w1, sasha_n1, vertex_deleter)

print("лучшее разбиение на клики:", sasha_best_solution_1)
# {'f': 51.0, 'cliques': [[0, 8, 7], [2, 4, 5], [9, 6]]}


лучшее разбиение на клики: ({0: [3], 1: [4, 2], 2: [1], 3: [6, 5, 9], 4: [8, 7, 0]}, 51.0)


In [470]:
obj_function(sasha_w1, {0: [5, 6, 9], 1: [3, 7], 2: [8, 0, 1], 3: [2, 4]})

48.0

In [472]:
obj_function(sasha_w1, {0: [0, 8, 7], 1: [2, 4, 5], 2: [9, 6], 3: [1], 4: [3]})

51.0

In [474]:
obj_function(sasha_w1, {0: [3], 1: [4, 2], 5: [1], 6: [6, 5, 9], 8: [8, 7, 0]})

51.0

In [476]:
sasha_n2 = 20
sasha_w2 = np.array(
    [[0.0, 7.0, -1e+20, 6.0, 10.0, 2.0, 7.0, 8.0, 9.0, 8.0, 2.0, 7.0, 1.0, 9.0, 8.0, 10.0, 5.0, 9.0, 2.0, 4.0], 
     [7.0, 0.0, 2.0, 9.0, 9.0, 4.0, 1.0, -1e+20, 7.0, 8.0, 2.0, 2.0, 3.0, 2.0, 1.0, 7.0, 9.0, 7.0, -1e+20, 4.0], 
     [-1e+20, 2.0, 0.0, -1e+20, 3.0, 2.0, 3.0, -1e+20, 6.0, 2.0, -1e+20, 9.0, 1.0, -1e+20, 10.0, 6.0, 3.0, -1e+20, 4.0, 5.0], 
     [6.0, 9.0, -1e+20, 0.0, 4.0, -1e+20, 1.0, 7.0, 3.0, 4.0, 7.0, 5.0, 4.0, 3.0, 1.0, 3.0, -1e+20, 9.0, 8.0, 8.0], 
     [10.0, 9.0, 3.0, 4.0, 0.0, -1e+20, 5.0, -1e+20, 4.0, 6.0, 8.0, 1.0, 7.0, -1e+20, 7.0, -1e+20, 10.0, 8.0, 3.0, 1.0], 
     [2.0, 4.0, 2.0, -1e+20, -1e+20, 0.0, -1e+20, 6.0, 1.0, 6.0, -1e+20, 10.0, 8.0, 3.0, 1.0, 1.0, 6.0, 3.0, 7.0, 1.0], 
     [7.0, 1.0, 3.0, 1.0, 5.0, -1e+20, 0.0, -1e+20, 2.0, 6.0, -1e+20, 6.0, -1e+20, 3.0, 1.0, 3.0, -1e+20, 6.0, 7.0, 10.0], 
     [8.0, -1e+20, -1e+20, 7.0, -1e+20, 6.0, -1e+20, 0.0, 3.0, 1.0, 7.0, 10.0, 7.0, -1e+20, -1e+20, -1e+20, -1e+20, 10.0, 6.0, 1.0], 
     [9.0, 7.0, 6.0, 3.0, 4.0, 1.0, 2.0, 3.0, 0.0, 10.0, 2.0, 6.0, 1.0, 8.0, 5.0, 6.0, -1e+20, 1.0, -1e+20, -1e+20], 
     [8.0, 8.0, 2.0, 4.0, 6.0, 6.0, 6.0, 1.0, 10.0, 0.0, 6.0, 4.0, 2.0, 5.0, -1e+20, -1e+20, -1e+20, 10.0, -1e+20, -1e+20], 
     [2.0, 2.0, -1e+20, 7.0, 8.0, -1e+20, -1e+20, 7.0, 2.0, 6.0, 0.0, 10.0, 5.0, 9.0, 1.0, -1e+20, 5.0, -1e+20, 6.0, 3.0], 
     [7.0, 2.0, 9.0, 5.0, 1.0, 10.0, 6.0, 10.0, 6.0, 4.0, 10.0, 0.0, 8.0, 3.0, 8.0, 5.0, 4.0, 6.0, -1e+20, -1e+20], 
     [1.0, 3.0, 1.0, 4.0, 7.0, 8.0, -1e+20, 7.0, 1.0, 2.0, 5.0, 8.0, 0.0, -1e+20, 8.0, -1e+20, 7.0, -1e+20, 4.0, 8.0], 
     [9.0, 2.0, -1e+20, 3.0, -1e+20, 3.0, 3.0, -1e+20, 8.0, 5.0, 9.0, 3.0, -1e+20, 0.0, -1e+20, 4.0, 10.0, 2.0, 6.0, 4.0], 
     [8.0, 1.0, 10.0, 1.0, 7.0, 1.0, 1.0, -1e+20, 5.0, -1e+20, 1.0, 8.0, 8.0, -1e+20, 0.0, 9.0, -1e+20, 4.0, -1e+20, -1e+20], 
     [10.0, 7.0, 6.0, 3.0, -1e+20, 1.0, 3.0, -1e+20, 6.0, -1e+20, -1e+20, 5.0, -1e+20, 4.0, 9.0, 0.0, 3.0, 6.0, 3.0, 2.0], 
     [5.0, 9.0, 3.0, -1e+20, 10.0, 6.0, -1e+20, -1e+20, -1e+20, -1e+20, 5.0, 4.0, 7.0, 10.0, -1e+20, 3.0, 0.0, 6.0, 2.0, 7.0], 
     [9.0, 7.0, -1e+20, 9.0, 8.0, 3.0, 6.0, 10.0, 1.0, 10.0, -1e+20, 6.0, -1e+20, 2.0, 4.0, 6.0, 6.0, 0.0, 9.0, 5.0], 
     [2.0, -1e+20, 4.0, 8.0, 3.0, 7.0, 7.0, 6.0, -1e+20, -1e+20, 6.0, -1e+20, 4.0, 6.0, -1e+20, 3.0, 2.0, 9.0, 0.0, 10.0], 
     [4.0, 4.0, 5.0, 8.0, 1.0, 1.0, 10.0, 1.0, -1e+20, -1e+20, 3.0, -1e+20, 8.0, 4.0, -1e+20, 2.0, 7.0, 5.0, 10.0, 0.0]])

# sasha_best_solution_2 = local_search(sasha_w2, sasha_n2, greedy_naive_solution)
sasha_best_solution_2 = local_search(sasha_w2, sasha_n2, vertex_deleter)
print("лучшее разбиение на клики:", sasha_best_solution_2)

# 'f': 321.0, 
# 'cliques': [[0, 1, 3, 4, 6, 8, 9, 11, 17], 
#             [10, 13, 16, 18, 19], 
#             [2, 14, 15], [12, 5, 7]]

лучшее разбиение на клики: ({0: [9, 5], 1: [14, 2, 4], 2: [13, 15, 0, 8, 1, 17, 3, 11, 6], 3: [19, 18, 10, 7, 12], 4: [16]}, 273.0)


In [478]:
# 3
obj_function(sasha_w2, {0: [9, 5], 1: [14, 2, 4], 2: [13, 15, 0, 8, 1, 17, 3, 11, 6], 3: [19, 18, 10, 7, 12], 4: [16]})

273.0

In [480]:
obj_function(sasha_w2, {0: [2, 14, 15], 1: [5, 12, 7], 2: [0, 1, 3, 4, 6, 8, 9, 11, 17], 3: [10, 13, 16, 18, 19]})


321.0

In [482]:
# 2
obj_function(sasha_w2, {0: [14, 2, 4, 1, 6], 
                        1: [9], 2: [5], 
                        3: [13, 15, 0, 8, 17, 3, 11], 
                        4: [19, 18, 10, 7, 12], 5: [16]})

219.0

In [444]:
# 1
obj_function(sasha_w2, {0: [2, 14, 15], 1: [11, 5, 12, 7], 2: [19, 6, 18, 17, 3, 0, 4], 3: [8, 9, 1], 4: [16, 13, 10]})
# {0: [2, 14, 15], 1: [11, 5, 12, 7], 2: [19, 6, 18, 17, 3, 0, 4], 3: [8, 9, 1], 4: [16, 13, 10]}

255.0

In [446]:
sasha_n3 = 20
sasha_w3 = np.array([
    [9.0, -1e+20, -1e+20, -1e+20, -1e+20, -1e+20, 3.0, -1e+20, -1e+20, -1e+20, -1e+20, -1e+20, 1.0, -1e+20, -1e+20, -1e+20, -1e+20, -1e+20, -1e+20, -1e+20], 
    [-1e+20, -1e+20, 10.0, 8.0, -1e+20, -1e+20, -1e+20, -1e+20, -1e+20, -1e+20, -1e+20, -1e+20, -1e+20, -1e+20, -1e+20, -1e+20, -1e+20, -1e+20, -1e+20, -1e+20], 
    [-1e+20, 10.0, 5.0, -1e+20, 1.0, 6.0, -1e+20, -1e+20, -1e+20, -1e+20, -1e+20, -1e+20, -1e+20, 8.0, -1e+20, -1e+20, 6.0, -1e+20, 8.0, 7.0], 
    [-1e+20, 8.0, -1e+20, 3.0, -1e+20, -1e+20, 9.0, -1e+20, -1e+20, -1e+20, 5.0, 5.0, -1e+20, -1e+20, -1e+20, -1e+20, -1e+20, -1e+20, -1e+20, -1e+20], 
    [-1e+20, -1e+20, 1.0, -1e+20, -1e+20, -1e+20, -1e+20, -1e+20, -1e+20, -1e+20, -1e+20, -1e+20, -1e+20, -1e+20, -1e+20, -1e+20, -1e+20, -1e+20, -1e+20, -1e+20], 
    [-1e+20, -1e+20, 6.0, -1e+20, -1e+20, -1e+20, 1.0, -1e+20, -1e+20, -1e+20, 8.0, -1e+20, -1e+20, -1e+20, -1e+20, -1e+20, -1e+20, -1e+20, 10.0, 10.0], 
    [3.0, -1e+20, -1e+20, 9.0, -1e+20, 1.0, 1.0, -1e+20, -1e+20, -1e+20, -1e+20, -1e+20, -1e+20, 5.0, -1e+20, -1e+20, -1e+20, 9.0, -1e+20, 9.0], 
    [-1e+20, -1e+20, -1e+20, -1e+20, -1e+20, -1e+20, -1e+20, -1e+20, 10.0, -1e+20, -1e+20, 4.0, -1e+20, -1e+20, -1e+20, -1e+20, -1e+20, -1e+20, 4.0, -1e+20], 
    [-1e+20, -1e+20, -1e+20, -1e+20, -1e+20, -1e+20, -1e+20, 10.0, -1e+20, -1e+20, -1e+20, -1e+20, -1e+20, 1.0, 4.0, -1e+20, -1e+20, -1e+20, -1e+20, -1e+20], 
    [-1e+20, -1e+20, -1e+20, -1e+20, -1e+20, -1e+20, -1e+20, -1e+20, -1e+20, -1e+20, -1e+20, -1e+20, 5.0, -1e+20, 7.0, -1e+20, -1e+20, -1e+20, -1e+20, -1e+20], 
    [-1e+20, -1e+20, -1e+20, 5.0, -1e+20, 8.0, -1e+20, -1e+20, -1e+20, -1e+20, -1e+20, -1e+20, -1e+20, 7.0, -1e+20, 3.0, -1e+20, -1e+20, -1e+20, -1e+20], 
    [-1e+20, -1e+20, -1e+20, 5.0, -1e+20, -1e+20, -1e+20, 4.0, -1e+20, -1e+20, -1e+20, -1e+20, -1e+20, 5.0, -1e+20, -1e+20, -1e+20, 9.0, 4.0, -1e+20], 
    [1.0, -1e+20, -1e+20, -1e+20, -1e+20, -1e+20, -1e+20, -1e+20, -1e+20, 5.0, -1e+20, -1e+20, -1e+20, -1e+20, -1e+20, -1e+20, -1e+20, -1e+20, -1e+20, -1e+20], 
    [-1e+20, -1e+20, 8.0, -1e+20, -1e+20, -1e+20, 5.0, -1e+20, 1.0, -1e+20, 7.0, 5.0, -1e+20, -1e+20, 5.0, 9.0, 2.0, -1e+20, -1e+20, -1e+20], 
    [-1e+20, -1e+20, -1e+20, -1e+20, -1e+20, -1e+20, -1e+20, -1e+20, 4.0, 7.0, -1e+20, -1e+20, -1e+20, 5.0, -1e+20, -1e+20, -1e+20, -1e+20, -1e+20, -1e+20], 
    [-1e+20, -1e+20, -1e+20, -1e+20, -1e+20, -1e+20, -1e+20, -1e+20, -1e+20, -1e+20, 3.0, -1e+20, -1e+20, 9.0, -1e+20, -1e+20, -1e+20, 10.0, -1e+20, -1e+20], 
    [-1e+20, -1e+20, 6.0, -1e+20, -1e+20, -1e+20, -1e+20, -1e+20, -1e+20, -1e+20, -1e+20, -1e+20, -1e+20, 2.0, -1e+20, -1e+20, -1e+20, 3.0, -1e+20, -1e+20], 
    [-1e+20, -1e+20, -1e+20, -1e+20, -1e+20, -1e+20, 9.0, -1e+20, -1e+20, -1e+20, -1e+20, 9.0, -1e+20, -1e+20, -1e+20, 10.0, 3.0, -1e+20, -1e+20, -1e+20], 
    [-1e+20, -1e+20, 8.0, -1e+20, -1e+20, 10.0, -1e+20, 4.0, -1e+20, -1e+20, -1e+20, 4.0, -1e+20, -1e+20, -1e+20, -1e+20, -1e+20, -1e+20, -1e+20, -1e+20], 
    [-1e+20, -1e+20, 7.0, -1e+20, -1e+20, 10.0, 9.0, -1e+20, -1e+20, -1e+20, -1e+20, -1e+20, -1e+20, -1e+20, -1e+20, -1e+20, -1e+20, -1e+20, -1e+20, -1e+20]
])

# sasha_best_solution_3 = local_search(sasha_w3, sasha_n3, greedy_naive_solution)
sasha_best_solution_3 = local_search(sasha_w3, sasha_n3, vertex_deleter)
print("лучшее разбиение на клики:", sasha_best_solution_3)

# 'f': 87.0, 
# 'cliques': [[0, 12], [1, 3], [10, 13, 15], [17, 11], [2, 18, 5], [19, 6], [8, 7], [9, 14]]


лучшее разбиение на клики: ({0: [4], 1: [12, 0], 2: [14, 9], 3: [8, 7], 4: [11, 17], 5: [16], 6: [13, 10, 15], 7: [6, 3], 8: [1], 9: [18, 5, 2], 10: [19]}, 79.0)


In [408]:
# 3
obj_function(sasha_w3, {0: [4], 1: [12, 0], 2: [14, 9], 3: [8, 7], 4: [11, 17], 5: [16], 6: [13, 10, 15], 7: [6, 3], 8: [1], 9: [18, 5, 2], 10: [19]})

79.0

In [410]:
# 1
obj_function(sasha_w3, {0: [6, 17], 1: [8, 7], 2: [11, 3], 3: [15, 13, 10], 4: [1, 2], 5: [0, 12], 6: [4], 7: [18, 5], 8: [14, 9], 9: [16], 10: [19]})
# {0: [2, 14, 15], 1: [11, 5, 12, 7], 2: [19, 6, 18, 17, 3, 0, 4], 3: [8, 9, 1], 4: [16, 13, 10]}

71.0

In [412]:
# 2
obj_function(sasha_w3, {0: [4], 1: [12, 0], 2: [1, 3], 3: [14, 9], 4: [8, 7], 5: [6, 17], 6: [11], 7: [16], 8: [13, 10, 15], 9: [18, 5, 2], 10: [19]})

78.0

In [454]:
print(f"w1: \n {w1} \n\nn1: {n1}")

w1: 
 [[0 1 2 0 3]
 [1 0 3 1 2]
 [2 3 0 4 1]
 [0 1 4 0 5]
 [3 2 1 5 0]] 

n1: 5


In [456]:
best_solution = local_search(w1, n1, greedy_naive_solution)
# best_solution = local_search(w2)
print("лучшее разбиение на клики:", best_solution)

лучшее разбиение на клики: ({0: [3, 4, 0, 2, 1]}, 22.0)


In [ ]:
def tabu_search(w, constructive_func, max_k, len_tl, save_iters=False):
    cur_solution = initial_partition(w)
    cur_objective = obj_function(w, cur_solution)
    
    tabu_lst, k = set(), 0
    best_solution, best_objective = cur_solution, cur_objective
    
    m = initialize_matrix(w, cur_solution)
    n, num_cliques = len(w), len(cur_solution)

    while k < max_k:
        i, j = np.unravel_index(np.argmax(M), M.shape)
        max_delta = m[i, j]
        
        if max_delta == 0: # не менять на <= 0 (?)
            break
        

    
    return best_solution, best_objective

In [29]:
list1 = [1, 2, 3, 4]
list2 = [3, 4, 5, 6]

[item for item in list2 if item not in list1]

[5, 6]